# Generated by Django 4.2.2 on 2023-07-06 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_is_available'),
        ('shop_cart', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcart',
            name='product',
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_cart.shopcart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='shopcart',
            name='products',
            field=models.ManyToManyField(through='shop_cart.CartProduct', to='products.product'),
        ),
    ]
