# Generated by Django 4.2.2 on 2023-07-01 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('delivered', 'Delivered')], default='confirmed', max_length=25)),
                ('product_quantity', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('is_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_sellers', to=settings.AUTH_USER_MODEL)),
                ('product', models.ManyToManyField(related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
