# Generated by Django 4.2.2 on 2023-07-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('delivered', 'Delivered')], default='confirmed', max_length=25)),
                ('product_quantity', models.IntegerField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
