# Generated by Django 4.2.2 on 2023-07-08 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='tecnologias', max_length=80),
            preserve_default=False,
        ),
    ]
